/*
 * File: app/model/OSMModel.js
 *
 * This file was generated by Sencha Architect version 2.2.3.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Sencha Touch 2.3.x library, under independent license.
 * License of Sencha Architect does not include license for Sencha Touch 2.3.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('demo3.model.DirectorioModel', {
    extend: 'Ext.data.Model',
	requires:["demo3.model.CategoriaModel"],
    config: {
        fields: [
            {
                name: "correo-electronico"
            },
            {
                name: "descripcion"
            },
            {
                name: "direccion"
            },
            {
                name: "fax"
            },
           	{
                name: "fecha-actualizacion"
            },
            {
                name: "horario"
            },
            {
                name: "identificador"
            },
            {
                name: "locale"
            },
            {
                name: "localizacion",
                convert: function(value, record) {
                			if (value.content){
			              		var coordenadas = value.content.split(" ");
			              		localizacion=coordenadas[0]+","+coordenadas[1];
                				console.log(coordenadas[0]+","+coordenadas[1]);
                			}else{
                				localizacion="No existe";
                			}
                			return localizacion;
            			}
            },
            {
                name: "nombre",
                mapping: "nombre.content"
            },
            {
                name: "direccion"
            },
            {
                name: "rdfa-id"
            },
           	{
                name: "telefono"
            },
            {
                name: "tipo"
            },
            {
                name: "url"
            },
            {
                name: "web"
            }
        ],
         hasMany: {model: 'CategoriaModel', name: 'categorias'}
    }
});