/*
 * File: app/store/OSMStore.js
 *
 * This file was generated by Sencha Architect version 2.2.3.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Sencha Touch 2.3.x library, under independent license.
 * License of Sencha Architect does not include license for Sencha Touch 2.3.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('demo2.store.OSMStore', {
    extend: 'Ext.data.Store',

    requires: [
        'demo2.model.OSMModel'
    ],

    config: {
        autoLoad: true,
        model: 'demo2.model.OSMModel',
        storeId: 'OSMStore',
        proxy: {
            type: 'jsonp',
            url: 'http://nominatim.openstreetmap.org/search?q=picos en+asturias&format=json',
            callbackKey: 'json_callback',
            reader: {
                type: 'json'
            }
        }
    }
});